# Generated by Django 6.0 on 2026-01-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='short_content',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
